# Generated by Django 6.0 on 2025-12-12 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_donnees', to=settings.AUTH_USER_MODEL)),
                ('agriculteur', models.ForeignKey(limit_choices_to={'role': 'agriculteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_recues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
