# Generated by Django 6.0 on 2025-12-12 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='updated_at',
            new_name='date_mise_a_jour',
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livraison',
            name='agence',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'livraison'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_gerees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='orders.commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('attribuee', 'Attribuée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('echec', 'Échec de livraison')], default='en_attente', max_length=20),
        ),
    ]
