# Generated by Django 6.0 on 2025-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(default='Légumes', max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
